<!doctype html>
<html>
	<head>
		<meta charset="utf8" />
		<meta name="author" content="Keombre" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<link rel="icon" href="<?=\lib\autoloader::ROOT?>/cropped-favicon-192x192.png">
		<title>Zadání maturitního kánonu</title>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<style>
			@media (min-width: 768px) {
				.my-buttons {
					margin-top: 100%;
				}
			}
			@media print {    
				.no-print, .no-print * {
					display: none !important;
				}
			}
			.my-buttons button {
				margin-top: 5px;
				margin-bottom: 5px;
			}
			.my-buttons button.btn-danger {
				margin-top: 25px;
			}
			#myBooks option {
				margin-bottom: 2px;
			}
		</style>
		<script>
			function checkIE() {
				var ua = window.navigator.userAgent;
				return (
					ua.indexOf('MSIE ') > -1 ||
					ua.indexOf('Trident/') > -1 ||
					ua.indexOf('Edge/') > -1);
			}
			function send(type) {
				let form = document.getElementById("form");
				if (checkIE()) {
					document.getElementById("form_state").value = type;
					document.getElementById("form").submit();
				} else if (form.reportValidity()) {
					document.getElementById("form_state").value = type;
					document.getElementById("form").submit();
				}
				return false;
			}
			$(document).ready(function(){
				$('[data-toggle="tooltip"]').tooltip();
				$("#search").on("keyup", function() {
					var value = $(this).val().toLowerCase();
					$("#book option").filter(function() {
						$(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
					});
				});
				$('#myModal').modal('show')
				$('#book').scrollPosReaload()
			});
			$.fn.scrollPosReaload = function(){
				if (localStorage) {
					var posReader = localStorage["posStorage"];
					if (posReader) {
						$(this).scrollTop(posReader);
						localStorage.removeItem("posStorage");
					}
					$(this).click(function(e) {
						localStorage["posStorage"] = $(this).scrollTop();
					});
					return true;
				}
				return false;
			}
		</script>
	</head>
	<body>
		<nav class="navbar navbar-default no-print">
			<div class="container">
				<div class="navbar-header">
					<a class="navbar-brand" href="/kanon" style="display: flex;">
						<img style="height: 50px; position: relative; top: -15px; margin-right: 15px" alt="Brand" src="/kanon/cropped-favicon-192x192.png">GPJP Maturitní kánon</a>
				</div>
			</div>
		</nav>
<?php if (isset($GLOBALS['state'])):?>
		<div class="container no-print" style="position: fixed; width: 100%; z-index: 5;">
			<div class="row">
				<div class="col-sm-offset-3 col-sm-6 no-print">
<?php if ($GLOBALS['state'] == "success"):?>
					<div id='alert' class="alert alert-success alert-dismissable">
						<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
<?=@$GLOBALS['message']?>
					</div>
<?php endif;?>
<?php if ($GLOBALS['state'] == "error"):?>
					<div id='alert' class="alert alert-danger alert-dismissable">
						<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
<?=@$GLOBALS['message']?>
					</div>
<?php endif;?>
				</div>
				<script>
					$("#alert").fadeTo(3000, 500).slideUp(500, function(){
						$("#alert").slideUp(500);
					});
				</script>
			</div>
		</div>
<?php if ($GLOBALS['state'] == "info"):?>
		<div id="myModal" class="modal fade in" role="dialog">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
						<h4 class="modal-title"><?=$GLOBALS['title']?></h4>
					</div>
					<div class="modal-body">
						<?=$GLOBALS['message']?>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">Zavřít</button>
					</div>
				</div>
			</div>
		</div>
<?php endif;?>
<?php endif;?>
