<!doctype html>
<html>
	<head>
		<meta charset="utf8" />
		<meta name="author" content="Keombre" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<link rel="apple-touch-icon" sizes="57x57" href="icons/apple-touch-icon-57x57.png">
		<link rel="apple-touch-icon" sizes="60x60" href="icons/apple-touch-icon-60x60.png">
		<link rel="apple-touch-icon" sizes="72x72" href="icons/apple-touch-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="76x76" href="icons/apple-touch-icon-76x76.png">
		<link rel="apple-touch-icon" sizes="114x114" href="icons/apple-touch-icon-114x114.png">
		<link rel="apple-touch-icon" sizes="120x120" href="icons/apple-touch-icon-120x120.png">
		<link rel="apple-touch-icon" sizes="144x144" href="icons/apple-touch-icon-144x144.png">
		<link rel="apple-touch-icon" sizes="152x152" href="icons/apple-touch-icon-152x152.png">
		<link rel="apple-touch-icon" sizes="180x180" href="icons/apple-touch-icon-180x180.png">
		<link rel="icon" type="image/png" sizes="32x32" href="icons/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="192x192" href="icons/android-chrome-192x192.png">
		<link rel="icon" type="image/png" sizes="16x16" href="icons/favicon-16x16.png">
		<link rel="manifest" href="site.webmanifest">
		<link rel="mask-icon" href="icons/safari-pinned-tab.svg" color="#474747">
		<link rel="shortcut icon" href="icons/favicon.ico">
		<meta name="apple-mobile-web-app-title" content="GPJP | Maturitn&iacute; K&aacute;non">
		<meta name="application-name" content="GPJP | Maturitn&iacute; K&aacute;non">
		<meta name="msapplication-TileColor" content="#9c9c9c">
		<meta name="msapplication-TileImage" content="icons/mstile-144x144.png">
		<meta name="msapplication-config" content="icons/browserconfig.xml">
		<meta name="theme-color" content="#ffffff">
		<title>GPJP | Maturitní Kánon</title>
		<script src="js/jquery.min.js"></script>
		<script src="js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<link rel="stylesheet" href="css/main.css" />
		<script src="js/main.js"></script>
	</head>
	<body>
		<nav class="navbar navbar-default no-print">
			<div class="container">
				<div class="navbar-header">
					<a class="navbar-brand" href="<?=\lib\autoloader::ROOT?>">
						<img src="<?=\lib\autoloader::ROOT?>cropped-favicon-192x192.png">GPJP Maturitní kánon</a>
				</div>
			</div>
		</nav>
		<noscript>
			<div class="container text-center">
				<h1 class="text-danger">JavaScript zakázán</h1><h2><strong>Tento web nebude fungovat.</strong></h1>
			</div>
		</noscript>
<?php if (isset($GLOBALS['state'])):?>
		<div id='alert' class="container no-print">
			<div class="row">
				<div class="col-sm-offset-3 col-sm-6 no-print">
<?php if ($GLOBALS['state'] == "success"):?>
					<div class="alert alert-success alert-dismissable">
						<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
<?=@$GLOBALS['message']?>
					</div>
<?php endif;?>
<?php if ($GLOBALS['state'] == "error"):?>
					<div class="alert alert-danger alert-dismissable">
						<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
<?=@$GLOBALS['message']?>
					</div>
<?php endif;?>
				</div>
			</div>
		</div>
<?php if ($GLOBALS['state'] == "info"):?>
		<div id="myModal" class="modal fade in" role="dialog">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
						<h4 class="modal-title"><?=$GLOBALS['title']?></h4>
					</div>
					<div class="modal-body">
						<?=$GLOBALS['message']?>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">Zavřít</button>
					</div>
				</div>
			</div>
		</div>
<?php endif;?>
<?php endif;?>
