<?php \lib\autoloader::getLayout('header')?>
			<form id="form" method="POST" class="no-print">
				<input type="hidden" name="state" id="form_state" />
				<?=\lib\csrf::printHTML("\t\t\t\t")?>
			</form>
			<div class="container">
				<div class="no-print panel panel-default">
					<div class="panel-body">
						<p>Kánon zkontrolujte, odešlete a poté vytiskněte.</p>
						<button class="btn btn-default" onclick="window.location.href='<?=\lib\autoloader::ROOT?>'">Zpět</button>
						<div class="pull-right btn-group"><?php if ($GLOBALS['print']):?>

							<button class="btn btn-success disabled" data-toggle="tooltip" data-placement="top" title="Kánon již byl odeslán">Odeslat</button>
							<button class="btn btn-primary" onclick="window.print()">Tisk</button>
<?php else:?>						
							<button class="btn btn-success" onclick="send('save')">Odeslat</button>
							<button class="btn btn-primary disabled" data-toggle="tooltip" data-placement="top" title="Před tiskem kánon odešlete">Tisk</button>
<?php endif?>
						</div>
					</div>
				</div>
				<?=\controller\preview::getBarcodeImg($GLOBALS['code'])?>

				<h3>Kánon <?=date("Y")?></h3>
				<table>
					<tr>
						<td>Jméno:&nbsp;&nbsp;</td>
						<td><strong><?= $GLOBALS['name'] . " " . $GLOBALS['surname']?></strong></td>
					</tr>
					<tr>
						<td>Třída: </td>
						<td><strong><?= $GLOBALS['class']?></strong></td>
					</tr>
				</table>
				<hr>
				<h4>Knihy</h4>
				<table class="table table-hover table-condensed">
					<thead>
						<tr>
							<th class="col-md-2">Autor</th>
							<th class="col-md-4">Dílo</th>
						</tr>
					</thead>
<?php
foreach($GLOBALS['books'] as $id => $book) {
	echo "\t\t\t\t\t<tr>\n\t\t\t\t\t\t<td>$book[author]</td>\n\t\t\t\t\t\t<td>$book[name]</td>\n\t\t\t\t\t</tr>" . PHP_EOL;
}
?>
				</table>
			</div>
		</form>
		<footer class="footer no-print">
			<div class="container text-center">
				<hr>
				<small><strong>Kánon:</strong> Mgr. Martina Urbanová, <strong>Koncept:</strong> Ing. David Švarc, <strong>Aplikace:</strong> Jan Wijnhorst <a target="_blank" href="https://github.com/keombre">@keombre</a></small>
				<small>
					<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">
						<img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/80x15.png" />
					</a>
					<br />Toto dílo podléhá licenci
					<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Uveďte původ-Neužívejte komerčně 4.0 Mezinárodní License</a>.
				</small>
			</div>
		</footer>
	</body>
</html>
