<?php \lib\autoloader::getTemplate('header')?>
<div class="container">
<button class="no-print btn btn-primary" onclick="window.print()">Tisk!</button>
<h3>Kánon <?=date("Y")?></h3>
<div class="table-responsive">
	<table style="table">
		<tr>
			<td>Jméno:&nbsp;&nbsp;</td>
			<td><strong><?= $GLOBALS['name'] . " " . $GLOBALS['surname']?></strong></td>
		</tr>
		<tr>
			<td>Třída: </td>
			<td><strong><?= $GLOBALS['class']?></strong></td>
		</tr>
	</table>
</div>
<hr>
<h4>Knihy</h4>
<table class="table table-hover">
  <thead>
    <tr>
      <th class="col-md-1">Období</th>
      <th class="col-md-2">Autor</th>
      <th class="col-md-4">Dílo</th>
    </tr>
  </thead>
<?php
	foreach($GLOBALS['books'] as $id => $book) {
		echo "<tr><td>$book[region]</td><td>$book[author]</td><td>$book[name]</td></tr>";
	}
?>
</table>
</div>
</form>
</body>
</html>
